version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: luna_app
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  composer:
    image: composer:2.6
    container_name: luna_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    entrypoint: ['composer' , 'install']
    networks:
      - laravel

  nginx:
    image: nginx:1.25
    container_name: luna_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: luna_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
